config/routes.rb
PublisherPictoricalCom::Application.routes.draw do

  match "/terms-and-conditions", :to => "pages#terms_and_conditions", :as => :terms_and_conditions, :via => :get
  match "/license-agreement", :to => "pages#license_agreement", :as => :license_agreement, :via => :get
  match "/artwork-guidelines", :to => "pages#artwork_guidelines", :as => :artwork_guidelines, :via => :get
  match "/privacy-policy", :to => "pages#privacy_policy", :as => :privacy_policy, :via => :get
  match "/website-disclaimer", :to => "pages#website_disclaimer", :as => :website_disclaimer, :via => :get
  match "/copyright-notice", :to => "pages#copyright_notice", :as => :copyright_notice, :via => :get
  match "/legal", :to => "pages#legal", :as => :legal, :via => :get
  match "/help", :to => "pages#help", :as => :help, :via => :get

  devise_for :users

  match "users/:id/mature", :to => "users#mature"
  match "users/:id/demature", :to => "users#demature"
  match "users/:id/make_admin", :to => "users#make_admin"
  match "users/:id/unmake_admin", :to => "users#unmake_admin"
  match "users/facepic", :to => "users#facepic", :as => :facepic  
  match "users/:id/facepic", :to => "users#facepic", :as => :facepic
  match "users/:id/add_facepic", :to => "users#add_facepic", :as => :add_facepic

  resources :users

  match "texts/:id/available", :to => "texts#make_available"
  match "texts/:id/unavailable", :to => "texts#make_unavailable"

  resources :texts

  match "trashes/:id/trashed_destroy", :to => "texts#trashed_destroy", :as => :trashed_destroy
  match "trashes/:id/trashed_undestroy", :to => "texts#trashed_undestroy", :as => :trashed_undestroy
  match "trashes/:id", :to => "texts#trashed_show", :as => :trashed
  match "trashes", :to => "texts#trashed_index", :as => :trashes

  resources :authors
  resources :translators

  match "invitations/reject", :to => "invitations#reject", :as => :reject_artist

  resources :invitations

  match "books/change", :to => "books#change", :as => :change_book
  match "books/review", :to => "books#review", :as => :review_book
  match "books/publish/:id", :to => "books#publish"
  match "books/revise/:id", :to => "books#revise"
  match "books/destroy/:id", :to => "books#destroy"
  match "books/:id/add_text", :to => "books#add_text"
  match "books/:id/remove_text", :to => "books#remove_text"
  match "books/:id/expire", :to => "books#expire", :as => :expire_book

  match "books/:id/epub",                         :to => "books#epub",                          :as => :epub
  match "books/:id/epub/content/00copyright",     :to => "books#epub_content_00copyright",      :as => :epub_content_00copyright
  match "books/:id/epub/content/02artist",        :to => "books#epub_content_02artist",         :as => :epub_content_02artist  
  match "books/:id/epub/content/03story",         :to => "books#epub_content_03story",          :as => :epub_content_03story
  match "books/:id/epub/content/images/download", :to => "books#epub_content_images_download",  :as => :epub_content_images_download
  match "books/:id/epub/metadata",                :to => "books#epub_metadata",                 :as => :epub_metadata
  match "books/:id/epub/toc",                     :to => "books#epub_toc",                      :as => :epub_toc

  resources :books

  match "illustrations/uploaded", :to => "illustrations#uploaded", :as => :illustration_uploaded
  match "illustrations/new/:type/:position", :to => "illustrations#new", :as => :new_illustration

  resources :illustrations

  match "cant", :to => "dashboard#cant", :as => :cant

  match "reminders/book_no_illustration", :to => "reminders#book_no_illustration", :as => :book_no_illustration

  root :to => "dashboard#start"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController


  def welcome

  end

  def start
    if (Time.now - current_user.created_at) < 10.seconds
      render "welcome", :layout => "simple"
    else
      if current_user.admin?
        render "admin"
      else
        @review_book = current_user.books.find_by_status("review")
        render "start", :layout => "simple"
      end
    end
  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/admin.html.haml
- title "Rockstar Admin"

- content_for :navbar do
  = render :partial => "layouts/adminbar"

app/views/dashboard/cant.html.haml
- title "Sorry you can't access this page"

%p
  - if notice
    notice
  - elsif alert
    alert
  - else
    Sorry you can't acces that page
%p
  = link_to "Go back.", :back

app/views/dashboard/start.html.haml
- title "Your Pictorical"

%p
  Hello #{current_user.name}!

  - unless @active_book.nil?
    %p
      You are illustrating
      %b= link_to @active_book.title, edit_book_path(@active_book)
  - else
    - unless @review_book.nil?
      %p
        You finished your book
        %b= link_to @review_book.title, @review_book
        #{time_ago_in_words(@review_book.updated_at)} ago.
      %p
        We take between 1 to 2 weeks to review your book. We will send you an email when it's ready.
    %p
      Be inspired by choosing your next story
      = link_to "here.", texts_path


%p.smaller.admin
  Boring? This is your start page and is under construction. What would you like to see here? Write us at
  = link_to "artists@pictorical.com", "mailto:artists@pictorical.com"
  with your ideas.

app/views/dashboard/welcome.html.haml
#welcome-canvas
  .inner
    %p Welcome to Pictorical!

    %p We are happy to welcome you to the Pictorical family. You are joining many talented emerging artists from all over the world, sharing our mission of illustrating the world's greatest stories.

    %p
      And now
      = link_to "let's start illustrating your first story.", texts_path