config/routes.rb
PublisherPictoricalCom::Application.routes.draw do

  match "/terms-and-conditions", :to => "pages#terms_and_conditions", :as => :terms_and_conditions, :via => :get
  match "/license-agreement", :to => "pages#license_agreement", :as => :license_agreement, :via => :get
  match "/artwork-guidelines", :to => "pages#artwork_guidelines", :as => :artwork_guidelines, :via => :get
  match "/privacy-policy", :to => "pages#privacy_policy", :as => :privacy_policy, :via => :get
  match "/website-disclaimer", :to => "pages#website_disclaimer", :as => :website_disclaimer, :via => :get
  match "/copyright-notice", :to => "pages#copyright_notice", :as => :copyright_notice, :via => :get
  match "/legal", :to => "pages#legal", :as => :legal, :via => :get
  match "/help", :to => "pages#help", :as => :help, :via => :get

  devise_for :users

  match "users/:id/mature", :to => "users#mature"
  match "users/:id/demature", :to => "users#demature"
  match "users/:id/make_admin", :to => "users#make_admin"
  match "users/:id/unmake_admin", :to => "users#unmake_admin"
  match "users/facepic", :to => "users#facepic", :as => :facepic  
  match "users/:id/facepic", :to => "users#facepic", :as => :facepic
  match "users/:id/add_facepic", :to => "users#add_facepic", :as => :add_facepic

  resources :users

  match "texts/:id/available", :to => "texts#make_available"
  match "texts/:id/unavailable", :to => "texts#make_unavailable"

  resources :texts

  match "trashes/:id/trashed_destroy", :to => "texts#trashed_destroy", :as => :trashed_destroy
  match "trashes/:id/trashed_undestroy", :to => "texts#trashed_undestroy", :as => :trashed_undestroy
  match "trashes/:id", :to => "texts#trashed_show", :as => :trashed
  match "trashes", :to => "texts#trashed_index", :as => :trashes

  resources :authors
  resources :translators

  match "invitations/reject", :to => "invitations#reject", :as => :reject_artist

  resources :invitations

  match "books/change", :to => "books#change", :as => :change_book
  match "books/review", :to => "books#review", :as => :review_book
  match "books/publish/:id", :to => "books#publish"
  match "books/revise/:id", :to => "books#revise"
  match "books/destroy/:id", :to => "books#destroy"
  match "books/:id/add_text", :to => "books#add_text"
  match "books/:id/remove_text", :to => "books#remove_text"
  match "books/:id/expire", :to => "books#expire", :as => :expire_book

  match "books/:id/epub",                         :to => "books#epub",                          :as => :epub
  match "books/:id/epub/content/00copyright",     :to => "books#epub_content_00copyright",      :as => :epub_content_00copyright
  match "books/:id/epub/content/02artist",        :to => "books#epub_content_02artist",         :as => :epub_content_02artist  
  match "books/:id/epub/content/03story",         :to => "books#epub_content_03story",          :as => :epub_content_03story
  match "books/:id/epub/content/images/download", :to => "books#epub_content_images_download",  :as => :epub_content_images_download
  match "books/:id/epub/metadata",                :to => "books#epub_metadata",                 :as => :epub_metadata
  match "books/:id/epub/toc",                     :to => "books#epub_toc",                      :as => :epub_toc

  resources :books

  match "illustrations/uploaded", :to => "illustrations#uploaded", :as => :illustration_uploaded
  match "illustrations/new/:type/:position", :to => "illustrations#new", :as => :new_illustration

  resources :illustrations

  match "cant", :to => "dashboard#cant", :as => :cant

  match "reminders/book_no_illustration", :to => "reminders#book_no_illustration", :as => :book_no_illustration

  root :to => "dashboard#start"

end

app/views/notifications/create_invitation.html.haml
%p= "Hi #{@invitation[:first_name]},"

- if @invitation[:specially].empty?

  %p I’ve looked at your portfolio and am a big fan of your work.

- else

  %p= "I’ve looked at your portfolio and am a big fan of your work, especially #{@invitation[:specially]}."


%p My name is Victor, co-founder of Pictorical. Nice to meet you. Pictorical publishes the world’s greatest stories, illustrated by emerging artists all over the world—just like you.

%p I’d like to invite you to join us. As part of Pictorical, you will be published worldwide and earn half of the profits from the sale of your books.

%p
  %b What's next?

%p
  To start illustrating your first story, go to
  = link_to "Pictorical's publishing tool", @url
  and sign up with your email address,
  = "#{@invitation[:email]}."

%p
  If you have any questions, you can ask us at
  = "#{link_to 'artists@pictorical.com', 'mailto:artists@pictorical.com'}.".html_safe

%p Looking forward to having you on board,

%p Best,

%p Victor, co-founder of Pictorical

%p
  PS: In case you are wondering, you received this email because you sent us your portfolio on
  = link_to "Pictorical's website", "http://artists.pictorical.com"

app/views/notifications/expire_book.html.haml
%p
  Hi #{@user.first_name},
%p
  Your book, "#{@book.title}," has expired.
%p
  Books expire after 2 weeks if you don't upload an illustration. We do this to give all of the artists the same opportunity to illustrate the texts they want.
%p
  You can go to
  = link_to "http://publisher.pictorical.com", "http://publisher.pictorical.com"
  to choose a new story to illustrate or if you want to pick "#{@book.texts.first.title}" again, then you have to wait until a week from today to begin illustrating the book again.
%p
  If you have any questions, or need help choosing your next story, you can reach us at
  = link_to "artists@pictorical.com", "mailto:artists@pictorical.com"
%p
  Kindest regards,
%p
  The Pictorical Team

app/views/notifications/illustration_feedback.text.haml
Hi #{@illustration.user.first_name},

Read the new feedback for your illustrations for #{@illustration.book.title} in

http://publisher.pictorical.com

A hug,

Victor and Mauko
Pictorical Team

app/views/notifications/new_book.text.haml
Hi #{@book.user_first_name},

You are illustrating #{@book.title}

What's next?

You can read your book and upload your illustrations in

= link_to "http://publisher.pictorical.com", "http://publisher.pictorical.com"

You can now start illustrating this book. Please remember to follow our Artwork Guidelines carefully, as they are very important for keeping the quality of our books awesome.

= link_to "Artwork Guidelines", "http://publisher.pictorical.com#{artwork_guidelines_path}"

Please upload your illustrations often, then we can give you feedback on them.

We will keep the book #{@book.title} reserved for you for two weeks. If you haven’t sent your first illustration by #{@expiration} then we will make the book available for another artist to illustrate it.

Feel free to contact us at artists@pictorical.com and tell us your progress and ask questions.

Thanks, and happy illustrating!

The Pictorical Team
Victor and Mauko

app/views/notifications/new_book_admin.html.haml
%p
  = @book.title unless @book.title.nil?
  (
  = @book.words unless @book.words.nil?
  )

%p
  By
  = @book.author.name unless @book.author.name.nil?
  = @book.author.last_name unless @book.author.last_name.nil?

%p
  Illustrated by
  = @user.first_name if @user.first_name?
  = @user.last_name if @user.last_name?

app/views/notifications/new_user_admin.html.haml
%p= "First name: #{@user.first_name}" if @user.first_name?
%p= "Last name: #{@user.last_name}" if @user.last_name?
%p= "Artistic name: #{@user.artistic_name}" if @user.artistic_name?

%p= "Country: #{@user.country}" if @user.country?

%p= "Birthdate: #{@user.birthdate.to_s}" if @user.birthdate?

%p
  Email:
  = link_to @user.email, @user.email if @user.email?

%p= "Paypal account: #{@user.paypal_account}" if @user.paypal_account?

%p
  Address:
  = @user.address_line_one if @user.address_line_one?
  %br
  = @user.address_line_two if @user.address_line_two?
  %br
  = "City: #{@user.city}" if @user.city?
  %br
  = "State: #{@user.state}" if @user.state?
  %br
  = "Zip: #{@user.zip}" if @user.zip?
  %br
  = "Country: #{@user.country}" if @user.country?

%p
  Portfolio:
  = link_to(@user.portfolio_url,@user.portfolio_url)  if @user.portfolio_url?

%p= "Artschool: #{@user.art_school_name}" if @user.art_school_name?

%p= "Twitter: #{@user.twitter}" if @user.twitter?

%p= "Accepted license agreement: #{@user.accepted_license_agreement.to_s}" if @user.accepted_license_agreement?

%p= "Created at: #{@user.created_at}" if @user.created_at?

app/views/notifications/publish_book.html.haml
%p= "Hi #{@book.user_first_name},"

%p
  Congratulations! Your book
  %b= @book.title
  has been published on the Apple iBook Store for the US, Canada, UK, Germany, France and Australia.

%p
  %b What's next?

%p
  We have set up a page for you and your books at
  =link_to "Pictorical.com", "http://pictorical.com"
  Share it with everybody, and tell your friends to “like” you and your books in Facebook.

%p
  We will send you monthly updates by email on the sales of your book, stating how many copies have been sold for each of your books, and we will pay you through your PayPal account,
  %b= @book.user_paypal_account
  , each time the money we owe you reaches $100 or more.

%p
  Are you ready to illustrate another book? We are!
  = link_to "Let's choose a new story.", "http://publisher.pictorical.com"

%p Congratulations!

%p
  The Pictorical Team
  %br
  Victor and Mauko

app/views/notifications/publish_book.text.haml
= "Hi #{@book.user_first_name},"

Congratulations! Your book
= @book.title
has been published on the Apple iBook Store for the US, Canada, UK, Germany, France and Australia.

What's next?

We have set up a page for you and your books at http://pictorical.com. Share it with everybody, and tell your friends to “like” you and your books in Facebook.

We will send you monthly updates by email on the sales of your book, stating how many copies have been sold for each of your books, and we will pay you through your PayPal account,
= @book.user_paypal_account
, each time the money we owe you reaches $100 or more.

Are you ready to illustrate another book? We are! Let’s choose a new story.
http://publisher.pictorical.com

Congratulations!

The Pictorical Team

Victor and Mauko

app/views/notifications/reject_artist.html.haml
%p= "Dear #{@name},"

%p
  Thank you for submitting your portfolio to Pictorial. Unfortunately, we will have to pass but appreciate the opportunity to view your illustrations. Please know that we can only accept a small percentage of the artists who submit to Pictorial, and that you should not feel discouraged.

%p
  We wish you luck placing your work elsewhere.

%p
  The Pictorical Team

app/views/notifications/reject_artist.text.haml
= "Dear #{@name},"

Thank you for submitting your portfolio to Pictorial. Unfortunately, we will have to pass but appreciate the opportunity to view your illustrations. Please know that we can only accept a small percentage of the artists who submit to Pictorial, and that you should not feel discouraged.

We wish you luck placing your work elsewhere.

The Pictorical Team

app/views/notifications/reminder_book_no_illustration.html.haml
%p
  Hi #{@user.first_name},

%p
  Just a friendly reminder that we are waiting for your first illustration for the book
  %b #{@book.title}.

%p
  We will reserve your book until #{@expiration}. If we haven't received your first illustration by then, we will make your book available to other artists.

%p
  You can read your book and upload your illustrations in
  = link_to "http://publisher.pictorical.com", "http://publisher.pictorical.com"

%p
  If you have any questions, you can reach us at
  = link_to "artists@pictorical.com", "mailto:artists@pictorical.com"

%p
  Kindest regards,

%p
  The Pictorical Team

app/views/notifications/review_book.text.haml
= "Hi #{@book.user_first_name},"

Thanks for sending us
= @book.title + "."
We will check that everything’s fine, build your book and publish it on the Apple iBook Store.

We will write you again when your book is published.

In the meantime, we would love to hear from you about your experience of using our website, and whether you have any recommendations and ideas that could help us improve it. You can email us at artists@pictorical.com.

You will hear from us soon,

The Pictorical Team

Victor and Mauko

app/views/notifications/welcome.html.haml
%p= "Hi #{@user.first_name},"

%p We very excited to have you on board!

%p
  %b What's next?

%p
  The first step is to choose a story to illustrate. Go to
  = link_to "Pictorical publisher", "http://publisher.pictorical.com"
  and choose from the many stories we have available.

%p Let's start working together to bring your illustrations to the world!

%p Happy story-choosing, and welcome to Pictorical.

%p
  The Pictorical Team
  %br
  Victor and Mauko

app/views/notifications/welcome.text.haml
= "Hi #{@user.first_name},"

We’re very excited to have you on board!

What's next?

The first step is to choose a story to illustrate. Go to http://publisher.pictorical.com and choose from the many stories we have available.

Let's start working together to bring your illustrations to the world!

Happy story-choosing, and welcome to Pictorical.

The Pictorical Team

Victor and Mauko